object Versions {
    val minSdk = 21
    val targetSdk = 29
    val compileSdk = 29
    val kotlin = "1.3.70"
    val dagger = "2.25.2"
    val rxKotlin = "2.4.0"
    val rxJava = "2.2.14"
    val rxAndroid = "2.1.1"
    val viewPager = "1.0.0"
    val javaxAnnotation = "1.0"
    val javaxInject = "1"
    val material = "1.1.0-rc01"
    val gson = "2.8.6"
    val hamcrest = "1.3"
    val arch_testing = "2.0.1"
    val navigationComponent = "2.1.0"
    val okHttp = "4.2.2"
    val androidAnnotations = "1.1.0"
    val recyclerView = "1.1.0"
    val androidx = "1.1.0"
    val drawerLayout = "1.1.0-alpha03"
    val retrofit = "2.6.2"
    val timber = "4.7.1"
    val glide = "4.10.0"
    val glideOkHttp = "4.10.0"
    val constraintLayout = "1.1.3"
    val room_android_x = "2.2.2"
    val bufferComponents = "0.3"
    val bufferAndroidUtils = "0.3"
    val counterView = "115e659a89"

    val workManagerTesting = "2.2.0"
    val robolectric = "3.5.1"
    val jUnit = "4.12"
    val jUnitAndroidX = "1.1.1"
    val assertJ = "3.14.0"
    val mockito = "2.28.2"
    val espresso = "3.2.0"
    val mockitoKotlin = "1.6.0"
    val mockitoKotlinTwo = "2.2.0"
    val mockitoAndroid = "3.1.0"
    val androidSupportRunner = "1.2.0"
    val androidSupportRules = "1.2.0"
    val espressoSupport = "1.0.0"
    val biscotti = "cc34682799"
    val uiAutomator = "2.1.3"
    val lifecyleVersion = "2.2.0"
}

object Deps {
    val recyclerview = "androidx.recyclerview:recyclerview:${Versions.recyclerView}"
    val appcompat = "androidx.appcompat:appcompat:${Versions.androidx}"
    val drawer_layout = "androidx.drawerlayout:drawerlayout:${Versions.drawerLayout}"
    val constraint_layout = "androidx.constraintlayout:constraintlayout:${Versions.constraintLayout}"
    val material = "com.google.android.material:material:${Versions.material}"
    val buffer_components = "org.buffer.android:android-components:${Versions.bufferComponents}"
    val buffer_android_utils = "org.buffer.android:android-utils:${Versions.bufferAndroidUtils}"
    val counter_view = "com.github.bufferapp:CounterView:${Versions.counterView}"
    val view_pager = "androidx.viewpager:viewpager:${Versions.viewPager}"
    val activity_ktx = "androidx.activity:activity-ktx:${Versions.androidx}"
    val life_cycle_extensions = "androidx.lifecycle:lifecycle-viewmodel-ktx:${Versions.lifecyleVersion}"

    val javax_annotation = "javax.annotation:jsr250-api:${Versions.javaxAnnotation}"
    val javax_inject = "javax.inject:javax.inject:${Versions.javaxInject}"

    val rx_kotlin = "io.reactivex.rxjava2:rxkotlin:${Versions.rxKotlin}"
    val rx_java = "io.reactivex.rxjava2:rxjava:${Versions.rxJava}"
    val rx_android = "io.reactivex.rxjava2:rxandroid:${Versions.rxAndroid}"
    val reactive_streams = "androidx.lifecycle:lifecycle-reactivestreams-ktx:${Versions.lifecyleVersion}"

    val kotlin = "org.jetbrains.kotlin:kotlin-stdlib-jdk8:${Versions.kotlin}"
    val gson = "com.google.code.gson:gson:${Versions.gson}"
    val timber = "com.jakewharton.timber:timber:${Versions.timber}"

    val glide = "com.github.bumptech.glide:glide:${Versions.glide}"
    val glide_okhttp = "com.github.bumptech.glide:okhttp3-integration:${Versions.glideOkHttp}"
    val glide_compiler = "com.github.bumptech.glide:compiler:${Versions.glide}"

    val room_runtime = "androidx.room:room-runtime:${Versions.room_android_x}"
    val room_compiler = "androidx.room:room-compiler:${Versions.room_android_x}"
    val room_rx_java = "androidx.room:room-rxjava2:${Versions.room_android_x}"
    val room_ktx = "androidx.room:room-ktx:${Versions.room_android_x}"

    val dagger = "com.google.dagger:dagger:${Versions.dagger}"
    val dagger_compiler = "com.google.dagger:dagger-compiler:${Versions.dagger}"
    val dagger_processor = "com.google.dagger:dagger-android-processor:${Versions.dagger}"

    val android_annotations = "androidx.annotation:annotation:${Versions.androidAnnotations}"

    val junit = "junit:junit:${Versions.jUnit}"
    val junit_androidx = "androidx.test.ext:junit:${Versions.jUnitAndroidX}"
    val junit_kotlin = "org.jetbrains.kotlin:kotlin-test-junit:${Versions.kotlin}"
    val hamcrest_core = "org.hamcrest:hamcrest-core:${Versions.hamcrest}"
    val hamcrest_library = "org.hamcrest:hamcrest-library:${Versions.hamcrest}"
    val hamcrest_integration = "org.hamcrest:hamcrest-integration:${Versions.hamcrest}"
    val mockito = "org.mockito:mockito-core:${Versions.mockito}"
    val mockito_kotlin = "com.nhaarman:mockito-kotlin:${Versions.mockitoKotlin}"
    val mockito_kotlin_two = "com.nhaarman.mockitokotlin2:mockito-kotlin:${Versions.mockitoKotlinTwo}"
    val mockito_android = "org.mockito:mockito-android:${Versions.mockitoAndroid}"
    val assertj = "org.assertj:assertj-core:${Versions.assertJ}"
    val robolectric = "org.robolectric:robolectric:${Versions.robolectric}"
    val room_testing = "androidx.room:room-testing:${Versions.room_android_x}"
    val arch_testing = "androidx.arch.core:core-testing:${Versions.arch_testing}"

    val support_runner = "androidx.test:runner:${Versions.androidSupportRunner}"
    val support_rules = "androidx.test:rules:${Versions.androidSupportRules}"
    val support_core = "androidx.test:core:${Versions.androidSupportRules}"
    val espresso_core = "androidx.test.espresso:espresso-core:${Versions.espresso}"
    val espresso_intents = "androidx.test.espresso:espresso-intents:${Versions.espresso}"
    val espresso_contrib = "androidx.test.espresso:espresso-contrib:${Versions.espresso}"
    val espresso_a11y = "androidx.test.espresso:espresso-accessibility:${Versions.espresso}"
    val espresso_support = "com.novoda:espresso-support:${Versions.espressoSupport}"
    val espresso_support_extras = "com.novoda:espresso-support-extras:${Versions.espressoSupport}"
    val biscotti = "com.github.bufferapp:Biscotti:${Versions.biscotti}"
    val ui_automator = "com.android.support.test.uiautomator:uiautomator-v18:${Versions.uiAutomator}"
}